### PR TITLE
Update Sponsor, SponsorGrid

### LINKED ISSUE #103: UPDATE SPONSORS WITH ACTUAL LOGOS

### PR DESCRIPTION
**Pull request by NovaSagittarii**
- [x] update sponsor component
- [x] update sponsor (content)
- [x] get pranked by the mysteries of tailwind
- [x] fix some broken buttons that i have no idea how they got this far without someone fixing them

### CODE REVIEW

**Comment by msclal** [comment]
the circles ones' links dont click

image

**Comment by msclal** [comment]
Also also btw make sure to add ```draggable={false}``` attribute to ```<Image/>``` tags

**Comment by NovaSagittarii** [comment]
> the circles ones' links dont click
> 
> image

image
well... i found the issue... some div is blocking the images 🗿

**Comment by NovaSagittarii** [comment]
bfhsdufjksdf
image

**Comment by minsooerickim** [comment]
looks amazinngggggg

**Pull request merged**
