### PR TITLE
Modal background dimming

### PR DESCRIPTION
**Pull request by NovaSagittarii**
wow dim happens

also the fixed items which are float right behave funny when the scrollbar disappears but the entire site doesnt shift left anymore

image

### CODE REVIEW

**Comment by NovaSagittarii** [comment]
man, something about the modal broke the unit tests :sob:

welp imma go fix that tomorrow

**Comment by NovaSagittarii** [comment]
cypress scam moment :moyai:

**Comment by NovaSagittarii** [comment]
oops i forgot the timeout, everything is so laggy on my end i forgot to test lol

**Comment by NovaSagittarii** [comment]
wtf i got scammed

**Comment by NovaSagittarii** [comment]
mfw test fail because they were meant to fire

**Comment by minsooerickim** [comment]
looks awesome

**Pull request merged**
